package se.sportswatch;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.*;
import se.sportswatch.Models.*;
import se.sportswatch.Repositories.*;
import java.util.*;
import java.io.IOException;
import java.util.stream.Collectors;

@Controller
public class TeamController{
    @Autowired // This means to get the bean called userRepository    
    private UserRepository userRepository;// Which is auto-generated by Spring, we will use it to handle the data

    @Autowired
    private TeamRepository teamRepository;

    @GetMapping("/teams")
    public String goToTeams(){
        return "teams";
    }
}